# Site settings
title:          hylinux
description:    "Posts about program."
baseurl:        
url:            "https://hylinux1024.github.io"

# Author
author:
  name:         hylinux1024
  url:          https://wecode.xyz
  email:        wecodexyz@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
