# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://hylinux1024.github.io
date_format: "ordinal"
title: Thinking Tech
author: hylinux 

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: hyinux1024
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: hylinux1024
    repo: jekyll-theme-solid
    oauth:
        client_id: c79c9ae57765adcce459
        client_secret: 09264b1c3c58033878872c924196898c9931a8e5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
